apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: frontend
  name: frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      enviroment: frontend
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        enviroment: frontend
    spec:
      containers:
      - image: linkheavy/frontend
        name: nginx
        ports:
        - containerPort: 3000
